### ISSUE TITLE
Exception while Fetching odds from multiple sources one after another.

### ISSUE THREAD

**Issue by srikanth-chitturi** [sbefort/json-odds-api#2]
One major issue we are facing is that some times there is an exception while fetching game data from multiple sources. I don't know what is causing this problem.

I am including my code , error and npm-debug.log file for your reference.
please run this code on your side and test it.

Thanks in Advance.
[error.txt](https://github.com/sbefort/json-odds-api/files/349188/error.txt)
[multipleodds.js.txt](https://github.com/sbefort/json-odds-api/files/349190/multipleodds.js.txt)
[npm-debug.log.txt](https://github.com/sbefort/json-odds-api/files/349191/npm-debug.log.txt)

**Comment by sbefort** [comment]
Duplicate issue, see https://github.com/sbefort/json-odds-api/issues/1
